### ISSUE TITLE
no profiles matched with the detected Application sync. skip this time

### ISSUE THREAD

**Issue by l4mb0san** [argoproj-labs/argocd-interlace#26]
Hi everyone, I have the following problem

This is my Application on ArgoCD:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  generation: 456
  name: unstoppable
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: git@github.com:myrepo/unstoppable.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

When I commit to change manifests, i received pod logs of argocd-interlace as below:
```
time="2023-07-27T03:16:52Z" level=debug msg="update event for app `unstoppable`"
time="2023-07-27T03:16:52Z" level=info msg="no profiles matched with the detected Application sync. skip this time."
time="2023-07-27T03:16:52Z" level=debug msg="key from queue: Application:argocd/unstoppable"
time="2023-07-27T03:16:52Z" level=debug msg="Check if new events in queue 0"
```

After that, I ran this command to check ApplicationProvenance, but see nothing.
```
$ kubectl get appprov -n argocd-interlace
No resources found in argocd-interlace namespace.
```

**What should I do next to be able to get the same result with https://github.com/argoproj-labs/argocd-interlace/blob/main/docs/example_scenario.md ?**

_Thanks for everyone's support._
